icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome6"

# BLOCKS

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
icons_format = "{icon}  "
format = " $icon $mem_total_used_percents.eng(w:2) ($mem_avail ) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "net"
format = "$icon   $signal_strength -- $ssid -- $ip"
format_alt = " $icon ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
[block.icons_overrides]
backlight = [
  "\uf676",
  "\uf0eb",
  "\uf185"
]

[[block]]
block = "battery"
format = "$icon $percentage {$time |}"
icons_format = "{icon}    "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d/%m %T') "
